name: Tag and Release

on:
  workflow_dispatch:

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9

      - name: Calculate next version
        id: calculate_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          dry_run: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Bump version
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          pnpm version "${{ steps.calculate_version.outputs.new_tag }}" --git-tag-version false
          git add package.json
          git commit -m "chore(project): Bump version to ${{ steps.calculate_version.outputs.new_tag }}"
          git push

  tag-and-release:
    runs-on: ubuntu-latest
    needs: bump-version
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Package extension
        run: pnpm run package

      - name: Publish extension to marketplace
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        run: pnpm run publish

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          artifacts: "recommended-settings-*.vsix"
          tag: ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
